#!/bin/bash

BOOK_CONTENT="/home/jovyan/content"
BOOK_CONFIG="${BOOK_CONTENT}/_config.yml"
if test -f $BOOK_CONFIG; then
    echo "This repository contains a Jupyter Book configuration."
    REF=$(git rev-parse HEAD)
    BOOK_INPUT="/home/jovyan/data/book-artifacts/$REF"
    mkdir ${BOOK_CONTENT}/_build
    cp -r ${BOOK_INPUT}/* ${BOOK_CONTENT}/_build
fi

exec "$@"